version: '3.5'
services:
  server:
    image: drone/drone:1.2.1
    environment:
    - DRONE_OPEN
    - DRONE_GITHUB_SERVER
    - DRONE_GITHUB_CLIENT_ID
    - DRONE_GITHUB_CLIENT_SECRET
    - DRONE_RUNNER_CAPACITY
    - DRONE_RPC_SECRET
    - DRONE_SERVER_HOST
    - DRONE_SERVER_PROTO
    - DRONE_TLS_AUTOCERT
    - DRONE_ADMIN
    ports:
    - 127.0.0.1:${LISTEN_PORT}:80/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - server-volume:/data:rw
  agent:
    image: drone/agent:1.2.1
    depends_on:
    - server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DRONE_RPC_SERVER=http://server:9000
    - DRONE_RPC_SECRET
    - DRONE_RUNNER_CAPACITY
volumes:
  server-volume: {}
