version: '3.5'
services:
  server:
    image: drone/drone:1.2.3
    environment:
    - DRONE_OPEN
    - DRONE_GITHUB_SERVER
    - DRONE_GITHUB_CLIENT_ID
    - DRONE_GITHUB_CLIENT_SECRET
    - DRONE_RUNNER_CAPACITY
    - DRONE_RPC_SECRET
    - DRONE_SERVER_HOST
    - DRONE_SERVER_PROTO
    - DRONE_TLS_AUTOCERT
    - DRONE_ADMIN
    - NO_PROXY
    - HTTP_PROXY
    - HTTPS_PROXY
    ports:
    - published: ${LISTEN_PORT}
      target: 80
      protocol: tcp
      mode: ingress
    volumes:
    - server-volume:/data:rw
    networks:
    - network
  agent:
    image: drone/agent:1.2.3
    depends_on:
    - server
    environment:
    - DRONE_RPC_SERVER=http://server:9000
    - DRONE_RPC_SECRET
    - DRONE_RUNNER_CAPACITY
    networks:
    - network
volumes:
  server-volume: {}
networks:
  network: {}
